# Build & publish Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: [main]        # solo cuando hagas push a main
  workflow_dispatch:        # permite lanzarlo manualmente

permissions:
  contents: read            # checkout
  pages: write              # publicar
  id-token: write           # firmar el deploy

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true     # para que PaperMod llegue al runner
          fetch-depth: 0

      - name: Configure Pages
        uses: actions/configure-pages@v5   # habilita Pages y define rutas

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.1'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public          # carpeta que genera Hugo
          retention-days: 7       # opcional

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
